# Generated by Django 3.1.1 on 2021-09-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
